---
- name: Fedora setup
  hosts: localhost
  become: true
  become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  become_method: ansible.builtin.sudo
  gather_facts: true
  vars_files:
    - vars/vars.yaml
    - vars/secret_vars.yaml
  tasks:
    - name: Add repositories
      ansible.builtin.include_tasks: tasks/1_repos.yaml

    - name: Machine configuration and certificates
      ansible.builtin.include_tasks: tasks/2_machine_and_certs.yaml

    - name: Operating System tweaks
      ansible.builtin.include_tasks: tasks/3_os_tweaks.yaml

    - name: Launch apps to create config
      ansible.builtin.include_tasks: tasks/4_app_launches.yaml

    - name: Install applications and codecs
      ansible.builtin.include_tasks: tasks/5_apps_codecs.yaml

    - name: Application configurations
      ansible.builtin.include_tasks: tasks/6_app_configs.yaml

  handlers: 
    - name: Reboot
      ansible.builtin.reboot:
        msg: "Rebooting machine in 5 seconds"
