---
- name: Fedora setup
  hosts: localhost
  become: true
  become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  become_method: ansible.builtin.sudo
  gather_facts: true
  vars_files:
    - vars/vars.yaml
    - vars/secret_vars.yaml
  tasks:
    - name: Install applications and codecs
      ansible.builtin.include_tasks: tasks/4_apps_codecs.yaml

    - name: Application configurations
      ansible.builtin.include_tasks: tasks/5_app_configs.yaml

  handlers: 
    - name: Reboot
      become_user: root
      ansible.builtin.shell: |
        echo -e "Rebooting machine in 5 seconds"
        sleep 5
        systemctl reboot

    - name: Update-grub
      become_user: root
      ansible.builtin.shell: grub2-mkconfig -o /boot/grub2/grub.cfg
