---
- name: Enable dnf utils
  become_user: root
  ansible.builtin.dnf:
    name: dnf-utils

- name: Enable 3rd party repositories
  become_user: root
  ansible.builtin.dnf:
    name:
      - fedora-workstation-repositories

- name: Check flatpak repo just in case
  ansible.builtin.shell: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# - name: Enable RPM Fusion repositories
#   become_user: root
#   ansible.builtin.dnf:
#     name:
#       - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{  fedora_ver }}.noarch.rpm
#       - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_ver }}.noarch.rpm
#     state: present

- name: Import RPM Fusion free GPG key
  become_user: root
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
    fingerprint: E9A4 91A3 DE24 7814 E7E0 67EA E06F 8ECD D651 FF2E

- name: Enable the RPM Fusion free repository
  become_user: root
  ansible.builtin.dnf:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_ver }}.noarch.rpm"
    state: present

- name: Import RPM Fusion nonfree GPG key
  become_user: root
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
    fingerprint: 79BD B88F 9BBF 7391 0FD4 095B 6A2A F961 9484 3C65

- name: Enable the RPM Fusion nonfree repository
  become_user: root
  ansible.builtin.dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_ver }}.noarch.rpm"
    state: present

- name: Vivaldi repo
  become_user: root
  ansible.builtin.yum_repository:
    name: vivaldi
    description: vivaldi
    baseurl: https://repo.vivaldi.com/archive/rpm/x86_64
    gpgkey: https://repo.vivaldi.com/archive/linux_signing_key.pub
    enabled: true

- name: Copr XONE repo  # Need to test
  become_user: root
  ansible.builtin.yum_repository:
    name: copr:copr.fedorainfracloud.org:raymondbaker:xone-dlundqvist
    description: Copr repo for xone-dlundqvist owned by raymondbaker
    baseurl: https://download.copr.fedorainfracloud.org/results/raymondbaker/xone-dlundqvist/fedora-$releasever-$basearch/
    gpgkey: https://download.copr.fedorainfracloud.org/results/raymondbaker/xone-dlundqvist/pubkey.gpg
    enabled: true  

- name: CoolerControl
  become_user: root
  ansible.builtin.yum_repository:
    name: copr:copr.fedorainfracloud.org:codifryed:CoolerControl
    description: Copr repo for CoolerControl owned by codifryed
    baseurl: https://download.copr.fedorainfracloud.org/results/codifryed/CoolerControl/fedora-$releasever-$basearch/
    gpgkey: https://download.copr.fedorainfracloud.org/results/codifryed/CoolerControl/pubkey.gpg
    enabled: true 

- name: GPU screen recorded
  become_user: root
  ansible.builtin.yum_repository:
    name: copr:copr.fedorainfracloud.org:jackgreiner:lug-helper
    description: Copr repo for CoolerControl owned by codifryed
    baseurl: https://download.copr.fedorainfracloud.org/results/codifryed/CoolerControl/fedora-$releasever-$basearch/
    gpgkey: https://download.copr.fedorainfracloud.org/results/codifryed/CoolerControl/pubkey.gpg
    enabled: true 
