---
# - name: Set performance profile
#   become_user: root
#   ansible.builtin.lineinfile:
#     path: /etc/default/grub
#     backrefs: true
#     regexp: '^(GRUB_CMDLINE_LINUX=(?!.*cpufreq.default_governor=performance).*)"$'
#     line: '\1 cpufreq.default_governor=performance"'

- name: Disable split_lock_detect
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backrefs: true
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*split_lock_detect=off).*)"$'
    line: '\1 split_lock_detect=off"'

- name: Set nvidia drm 
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backrefs: true
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*nvidia-drm.modset=1).*)"$'
    line: '\1 nvidia-drm.modset=1"'

- name: Set rd.driver.blacklist
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?:(?!rd.driver.blacklist=nouveau,nova_core).)*?)"$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 rd.driver.blacklist=nouveau,nova_core"'
    backup: true
    backrefs: true

- name: Set modprobe.blacklist
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?:(?!modprobe.blacklist=nouveau,nova_core).)*?)"$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 modprobe.blacklist=nouveau,nova_core"'
    backup: true
    backrefs: true
  notify: Update-grub

- name: Disable SELinux
  become_user: root
  ansible.builtin.lineinfile: 
    path: /etc/selinux/config 
    regexp: '^SELINUX=.*' 
    line: 'SELINUX=disabled'
  notify: Reboot
