---
- name: Disable split_lock_detect #required for games like God of War to prevent stutters
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?:(?!split_lock_detect=off).)*?)"$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 split_lock_detect=off"'
    backup: true
    backrefs: true

- name: Set nvidia-drm.modset
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?:(?!nvidia-drm.modset=1).)*?)"$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 nvidia-drm.modset=1"'
    backup: true
    backrefs: true

- name: Set rd.driver.blacklist
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?:(?!rd.driver.blacklist=nouveau,nova_core).)*?)"$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 rd.driver.blacklist=nouveau,nova_core"'
    backup: true
    backrefs: true

- name: Set modprobe.blacklist
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?:(?!modprobe.blacklist=nouveau,nova_core).)*?)"$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 modprobe.blacklist=nouveau,nova_core"'
    backup: true
    backrefs: true

- name: Update grub
  become_user: root
  ansible.builtin.shell: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
