---
- name: Codecs
  become_user: root
  ansible.builtin.dnf:
    name:
      - gstreamer1-devel
      - gstreamer1-plugins-base-tools
      - gstreamer1-doc
      - gstreamer1-plugins-base-devel
      - gstreamer1-plugins-good
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free-devel
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-ugly
      - x265-libs
      - libde265
      - libavcodec-freeworld
      - libheif-freeworld

- name: install lug-helper
  become_user: root
  ansible.builtin.shell: |
    yes | dnf copr enable jackgreiner/lug-helper 
    yes | dnf install lug-helper

- name: Other applications
  become_user: root
  ansible.builtin.dnf:
    name:
      - bsdtar
      - fastfetch
      - powerline
      - btop
      - s-tui
      - mangohud
      - steam
      - lutris
      - kmod-v4l2loopback #obs virtual camera
      - coolercontrol
      - vivaldi-stable

- name: Install Gaming Flatpaks
  community.general.flatpak:
    name:
      - com.heroicgameslauncher.hgl
      - com.teamspeak.TeamSpeak3
      - net.davidotek.pupgui2 #ProtonUp-QT
      - com.obsproject.Studio
      - io.github.benjamimgois.goverlay

- name: Other Flatpaks
  community.general.flatpak:
    name: 
      - com.github.dail8859.NotepadNext
      - org.localsend.localsend_app

- name: xone clone
  ansible.builtin.git:
    repo: https://github.com/dlundqvist/xone
    dest: "{{ user_home }}/Downloads/xone"
    single_branch: yes
    version: master

- name: xone
  become_user: root
  ansible.builtin.shell: |
    cd '{{ user_home }}/Downloads/xone'
    ./install.sh

- name: xone firmware
  become_user: root
  ansible.builtin.expect:
    chdir: "{{ user_home }}/Downloads/xone/install"
    command: ./firmware.sh
    responses:
      "Press enter to continue!": ""

- name: Notify to close steam manually
  ansible.builtin.debug: 
    msg: "Please wait for steam to start up, once you see the login screen close it manually and the play will continue."

- name: Start steam
  ansible.builtin.shell: steam
