---
- name: Remove unwanted packages
  ansible.builtin.package:
    name:
      - tuned
      - amd-gpu-firmware
      - atheros-firmware
    state: absent

- name: Codecs and tools
  become_user: root
  ansible.builtin.dnf:
    name:
      - gstreamer1-devel
      - gstreamer1-plugins-base-tools
      - gstreamer1-doc
      - gstreamer1-plugins-base-devel
      - gstreamer1-plugins-good
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free-devel
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-ugly
      - x265-libs
      - libde265
      - libva-utils
      - libavcodec-freeworld
      - libheif-freeworld
      - libva-intel-media-driver
      - igt-gpu-tools
      - lm_sensors

- name: install lug-helper
  become_user: root
  ansible.builtin.shell: |
    yes | dnf copr enable jackgreiner/lug-helper 
    yes | dnf install lug-helper
  when: starcitizen == "enabled"

- name: Other applications
  become_user: root
  ansible.builtin.dnf:
    name:
      - bsdtar
      - fastfetch
      - powerline
      - btop
      - s-tui
      - mangohud
      - steam
      - lutris
      - kmod-v4l2loopback #obs virtual camera
      - coolercontrol
      - vivaldi-stable

- name: Install Gaming Flatpaks
  community.general.flatpak:
    name:
      - com.heroicgameslauncher.hgl
      - com.teamspeak.TeamSpeak3
      - net.davidotek.pupgui2 #ProtonUp-QT
      - com.obsproject.Studio
      - io.github.benjamimgois.goverlay
      - io.github.radiolamp.mangojuice

- name: Other Flatpaks
  community.general.flatpak:
    name: 
      - com.github.dail8859.NotepadNext
      - org.localsend.localsend_app

# rnnoise 
- name: Create rnnoise directory if it does not exist
  ansible.builtin.file:
    path: "{{ user_home }}/.config/pipewire/pipewire.conf.d/"
    state: directory
    mode: '0755'

- name: Copy rnnoise config file
  ansible.builtin.template:
    src: customization/templates/denoising.j2
    dest: "{{ user_home }}/.config/pipewire/pipewire.conf.d/99-input-denoising.conf"  

- name: Download rnnoise # need to add check for latest version
  ansible.builtin.get_url:
    url: https://github.com/werman/noise-suppression-for-voice/releases/download/v1.10/linux-rnnoise.zip
    dest: "{{ user_home }}/Downloads"
    mode: '0644'

- name: Unarchive rnnoise
  ansible.builtin.unarchive:
    src: "{{ user_home }}/Downloads/linux-rnnoise.zip"
    dest: "{{ user_home }}/Downloads/"

- name: Copy rnnoise .so file
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  loop: 
    - src: "{{ user_home }}/Downloads/linux-rnnoise/ladspa/librnnoise_ladspa.so"
      dest: "{{ user_home }}/bin/librnnoise_ladspa.so"
    - src: "{{ user_home }}/Downloads/linux-rnnoise/rnnoise_mono.lv2/librnnoise_mono.so"
      dest: "{{ user_home }}/bin/librnnoise_mono.so"
    - src: "{{ user_home }}/Downloads/linux-rnnoise/rnnoise_stereo.lv2/librnnoise_stereo.so"
      dest: "{{ user_home }}/bin/librnnoise_stereo.so"

- name: Restart pipewire and cleanup # need to add check for latest version
  become_user: root
  ansible.builtin.shell: |
    systemctl restart --user pipewire.service
    rm ./linux_rnnoise.zip && rm -rf ./linux-rnnoise

# xone
- name: xone clone
  ansible.builtin.git:
    repo: https://github.com/dlundqvist/xone
    dest: "{{ user_home }}/Downloads/xone"
    single_branch: yes
    version: master
  when: xboxadapter == "enabled"

- name: xone
  become_user: root
  ansible.builtin.shell: |
    cd '{{ user_home }}/Downloads/xone'
    ./install.sh
  when: xboxadapter == "enabled"

- name: xone firmware
  become_user: root
  ansible.builtin.expect:
    chdir: "{{ user_home }}/Downloads/xone/install"
    command: ./firmware.sh
    responses:
      "Press enter to continue!": ""
  when: xboxadapter == "enabled"

- name: Notify to close steam manually
  ansible.builtin.debug: 
    msg: "Please wait for steam to start up, once you see the login screen close it manually and the play will continue."

- name: Start steam
  ansible.builtin.shell: steam
