---
- name: Start steam, exit steam when prompted to login.
  ansible.builtin.shell: steam

# - name: wait for steam
#   ansible.builtin.pause:
#     prompt: "Waiting on Steam to install things"
#     minutes: 5

# - name: Close steam
#   ansible.builtin.shell: killall -s TERM steam
