---
- name: Check XDG session
  ansible.builtin.shell: echo $XDG_SESSION_TYPE
  register: xdg_session

- name: Check if Plasma Workspace X11 is installed
  ansible.builtin.shell: dnf list --installed plasma-workspace-x11 | awk -F"." 'NR==2 {print $1}'
  register: x11_installation

- name: Install X11 in KDE (Better for Gaming)
  become_user: root
  ansible.builtin.dnf:
    name:
      - plasma-workspace-x11
  when: xdg_session.stdout != "x11" and x11_installation.stdout != "plasma-workspace-x11"

- name: Print Message
  ansible.builtin.debug: 
    msg: "After the X11 installation log out of the Plasma Wayland session and log into a Plasma X11 session, then run the `fedora_kde_part1.yaml` play!"
  when: xdg_session.stdout != "x11"
