---
- name: Check XDG session
  ansible.builtin.shell: echo $XDG_SESSION_TYPE
  register: xdg_session

- name: Message when not X11 session
  ansible.builtin.debug:
    msg: "You need to be in a 'X11' session instead of 'Wayland'!\nAfter the X11 installation log into X11 session and run this again!"
  when: xdg_session.stdout != "x11"

- name: Check if Plasma Workspace X11 is installed
  ansible.builtin.shell: dnf list --installed plasma-workspace-x11 | awk -F"." 'NR==2 {print $1}'
  register: x11_installation

- name: Install X11 in KDE (Better for Gaming)
  become_user: root
  ansible.builtin.dnf:
    name:
      - plasma-workspace-x11
  when: xdg_session.stdout != "x11" and x11_installation.stdout != "plasma-workspace-x11"

- name: End the play if requirements aren't met
  ansible.builtin.meta: end_play
  when: xdg_session.stdout != "x11"
